FROM node:20-alpine@sha256:f598378b5240225e6beab68fa9f356db1fb8efe55173e6d4d8153113bb8f333c

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy source
COPY . .

# Ensure local script can run in container
RUN chmod +x /app/docker-entrypoint.sh

# Expose port
EXPOSE 3000

# Run dev server
CMD ["/app/docker-entrypoint.sh"]
