// Generated by {{generatedBy}} at {{timestampUtc}}.
import { {{className}} } from '../adapters/{{camelName}}Adapter.js';

describe('{{className}} scaffold', () => {
  it('returns null by default until transport is wired', async () => {
    const adapter = new {{className}}();
    await expect(adapter.read('doc-1')).resolves.toBeNull();
  });
});
