// Generated by {{generatedBy}} at {{timestampUtc}}.
// Adapters should depend on ports, not concrete callers.

import type { {{pascalName}}Port } from '../ports/{{camelName}}Port.js';

export class {{className}} implements {{pascalName}}Port {
  async read(_documentId: string): Promise<Uint8Array | null> {
    return null;
  }
}
