// Generated by {{generatedBy}} at {{timestampUtc}}.
import type { {{className}} } from '../ports/{{camelName}}Port.js';

describe('{{className}} scaffold', () => {
  it('supports nullable binary reads', async () => {
    const port: {{className}} = {
      async read(_documentId: string) {
        return null;
      },
    };

    await expect(port.read('doc-1')).resolves.toBeNull();
  });
});
