// Generated by {{generatedBy}} at {{timestampUtc}}.
// Port contracts live in collab-server/src/ports and are implemented by adapters.

export interface {{className}} {
  read(documentId: string): Promise<Uint8Array | null>;
}
