#!/usr/bin/env node
import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const repoRoot = path.resolve(__dirname, '..', '..')

const args = new Set(process.argv.slice(2))
const checkOnly = args.has('--check')

const sourcePath = path.join(repoRoot, 'backend', 'openapi.contract.json')
const outputPath = path.join(
  repoRoot,
  'frontend',
  'src',
  'lib',
  'api',
  'generated',
  'openapi-contracts.ts',
)

function quoteString(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function formatKey(key) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : quoteString(key)
}

function refToSchemaName(ref) {
  if (typeof ref !== 'string') {
    return null
  }
  const match = ref.match(/^#\/components\/schemas\/(.+)$/)
  return match ? match[1] : null
}

function applyNullable(type, schema) {
  return schema?.nullable ? `${type} | null` : type
}

function schemaToType(schema) {
  if (!schema || typeof schema !== 'object') {
    return 'unknown'
  }

  if ('$ref' in schema) {
    const schemaName = refToSchemaName(schema.$ref)
    if (!schemaName) {
      return 'unknown'
    }
    return `OpenApiSchema<${quoteString(schemaName)}>`
  }

  if ('const' in schema) {
    return quoteLiteral(schema.const)
  }

  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    const enumType = schema.enum.map(quoteLiteral).join(' | ')
    return applyNullable(enumType, schema)
  }

  if (Array.isArray(schema.allOf) && schema.allOf.length > 0) {
    const parts = schema.allOf.map(schemaToType)
    return applyNullable(parts.join(' & '), schema)
  }

  if (Array.isArray(schema.anyOf) && schema.anyOf.length > 0) {
    const parts = schema.anyOf.map(schemaToType)
    return applyNullable(parts.join(' | '), schema)
  }

  if (Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
    const parts = schema.oneOf.map(schemaToType)
    return applyNullable(parts.join(' | '), schema)
  }

  if (schema.type === 'array') {
    const itemsType = schema.items ? schemaToType(schema.items) : 'unknown'
    return applyNullable(`(${itemsType})[]`, schema)
  }

  if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    return applyNullable(objectSchemaToType(schema), schema)
  }

  if (Array.isArray(schema.type)) {
    const parts = schema.type.map((entry) => primitiveType(entry))
    const rendered = parts.filter(Boolean).join(' | ')
    return rendered || 'unknown'
  }

  if (typeof schema.type === 'string') {
    return applyNullable(primitiveType(schema.type), schema)
  }

  return 'unknown'
}

function primitiveType(type) {
  switch (type) {
    case 'string':
      return 'string'
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'null':
      return 'null'
    default:
      return 'unknown'
  }
}

function quoteLiteral(value) {
  if (typeof value === 'string') {
    return quoteString(value)
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value)
  }
  if (value === null) {
    return 'null'
  }
  return 'unknown'
}

function objectSchemaToType(schema) {
  const properties = schema.properties && typeof schema.properties === 'object' ? schema.properties : {}
  const required = new Set(Array.isArray(schema.required) ? schema.required : [])
  const keys = Object.keys(properties).sort()
  const hasAdditionalProperties = Object.prototype.hasOwnProperty.call(
    schema,
    'additionalProperties',
  )

  // Avoid emitting bare `{}` which fails lint (`@typescript-eslint/ban-types`).
  if (keys.length === 0) {
    if (!hasAdditionalProperties || schema.additionalProperties === true) {
      return 'Record<string, unknown>'
    }
    if (schema.additionalProperties === false) {
      return 'Record<string, never>'
    }
    return `Record<string, ${schemaToType(schema.additionalProperties)}>`
  }

  const lines = ['{']
  for (const key of keys) {
    const propertySchema = properties[key]
    const optionalToken = required.has(key) ? '' : '?'
    const propertyType = schemaToType(propertySchema)
    lines.push(`  ${formatKey(key)}${optionalToken}: ${propertyType};`)
  }

  if (schema.additionalProperties) {
    const additionalType =
      schema.additionalProperties === true ? 'unknown' : schemaToType(schema.additionalProperties)
    lines.push(`  [key: string]: ${additionalType};`)
  }

  lines.push('}')
  return lines.join('\n')
}

function renderContractsFile(openApiDocumentRaw, schemas) {
  const sourceHash = createHash('sha256').update(openApiDocumentRaw).digest('hex')
  const schemaNames = Object.keys(schemas).sort()

  const sections = []
  sections.push('// AUTO-GENERATED FILE. DO NOT EDIT.')
  sections.push('// Generated by scripts/api_contracts/generate_frontend_contracts.mjs')
  sections.push(`// Source: backend/openapi.contract.json (sha256: ${sourceHash})`)
  sections.push('')
  sections.push('export interface OpenApiSchemas {')
  for (const schemaName of schemaNames) {
    sections.push(`  ${formatKey(schemaName)}: ${schemaToType(schemas[schemaName])};`)
  }
  sections.push('}')
  sections.push('')
  sections.push('export type OpenApiSchema<TName extends keyof OpenApiSchemas> = OpenApiSchemas[TName]')
  sections.push('')

  return `${sections.join('\n')}`
}

async function main() {
  const sourceRaw = (await fs.readFile(sourcePath, 'utf8')).replace(/^\uFEFF/, '')
  const sourceJson = JSON.parse(sourceRaw)
  const schemas = sourceJson?.components?.schemas

  if (!schemas || typeof schemas !== 'object') {
    throw new Error('OpenAPI source is missing components.schemas')
  }

  const rendered = renderContractsFile(sourceRaw, schemas)

  if (checkOnly) {
    let current = null
    try {
      current = await fs.readFile(outputPath, 'utf8')
    } catch {
      current = null
    }

    if (current !== rendered) {
      console.error('Generated contracts are out of date.')
      console.error('Run: npm run generate:api-contracts')
      process.exit(1)
    }
    console.log('Generated contracts are up to date.')
    return
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await fs.writeFile(outputPath, rendered, 'utf8')
  console.log(`Generated frontend OpenAPI contracts: ${outputPath}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
