"""Smoke tests for {{className}} controller scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
"""

from app.web.controllers.{{scope}}.{{moduleName}}_controller import {{className}}, build_router


def test_{{scope}}_{{testName}}_controller_scaffold_smoke() -> None:
    controller = {{className}}()
    assert controller.health_payload()["status"] == "ok"
    assert build_router().prefix == "{{routePrefix}}"
