"""{{className}} controller scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
Context: {{context}}.
"""

from __future__ import annotations

from fastapi import APIRouter


class {{className}}:
    """HTTP orchestration boundary for {{context}} workflows."""

    def health_payload(self) -> dict[str, str]:
        return {"controller": "{{className}}", "status": "ok"}


def build_router() -> APIRouter:
    controller = {{className}}()
    router = APIRouter(prefix="{{routePrefix}}", tags=["{{routerTag}}"])

    @router.get("/health")
    def health() -> dict[str, str]:
        return controller.health_payload()

    return router
