"""{{className}} policy scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
Context: {{context}}.
"""

from __future__ import annotations


class {{className}}:
    """Policy guard for {{context}} use-cases."""

    def allows(self, *, action: str, role: str) -> bool:
        """Default boundary-compliant policy: deny-by-default except admins."""
        _ = action
        return role in {"admin", "system_admin"}
