"""Smoke tests for {{className}} policy scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
"""

from app.policy.{{moduleName}} import {{className}}


def test_{{testName}}_policy_scaffold_smoke() -> None:
    policy = {{className}}()
    assert policy.allows(action="read", role="admin") is True
    assert policy.allows(action="read", role="viewer") is False
