"""{{className}} repository scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
Context: {{context}}.
"""

from __future__ import annotations

from sqlalchemy.orm import Query

from app.models import {{modelClass}}
from app.repositories.base import BaseRepository


class {{className}}(BaseRepository):
    """Repository boundary for {{modelClass}} aggregate."""

    def query(self) -> Query:
        return self.db.query({{modelClass}})
