"""Smoke tests for {{className}} repository scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
"""

from app.repositories.{{moduleName}}_repository import {{className}}


def test_{{testName}}_repository_scaffold_smoke() -> None:
    assert {{className}}.__name__ == "{{className}}"
