"""Smoke tests for {{className}} service scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
"""

from app.services.{{moduleName}}_service import {{className}}


def test_{{testName}}_service_scaffold_smoke() -> None:
    service = {{className}}()
    assert service.execute() is None
