"""{{className}} service scaffold.

Generated by {{generatedBy}} at {{timestampUtc}}.
Context: {{context}}.
"""

from __future__ import annotations


class {{className}}:
    """Service boundary for {{context}} workflows."""

    def execute(self) -> None:
        """Run the default {{moduleName}} workflow."""
        return None
