// Generated by {{generatedBy}} at {{timestampUtc}}.
// Keep feature logic inside this boundary; expose only use-case functions.

export interface {{interfaceName}} {
  describeBoundary: () => string
}

export function create{{interfaceName}}(): {{interfaceName}} {
  return {
    describeBoundary: () => '{{featureDir}}',
  }
}
