"""Domain layer package.

This package holds domain-centric interfaces and models that should stay
independent from transport and infrastructure concerns.
"""

from app.domain.aggregates import (
    DocumentAggregate,
    InvitationAggregate,
    ReviewAggregate,
)
from app.domain.capabilities import (
    AnyPermissionCapability,
    CanAssignCompanies,
    CanPublish,
    CustomerUserCapability,
    DocumentAccessCapability,
    InternalUserCapability,
    ManageUserCapability,
    PermissionCapability,
    ReviewApprovalCapability,
    RoleCapability,
)
from app.domain.factories import (
    DocumentFactory,
    InvitationFactory,
    VersionFactory,
)
from app.domain.result import Result
from app.domain.specifications import (
    CustomerInvitationTenantSpec,
    DateRangeSpec,
    DocumentDraftOrActiveSpec,
    DocumentDraftStatusSpec,
    InvitationPendingStatusSpec,
    InvitationResendableSpec,
    ManagerVisibilityRoleSpec,
    ReviewApprovableVersionSpec,
    ReviewPendingStatusSpec,
    ReviewSubmitterMatchesSpec,
    RoleAccessSpec,
    TenantScopeSpec,
    VisibilitySpec,
)
from app.domain.states import (
    ActiveDocumentStage,
    ApprovedDocumentStage,
    ApprovedReviewStage,
    ArchivedDocumentStage,
    CancelledReviewStage,
    DocumentStage,
    DraftDocumentStage,
    NoReviewStage,
    PendingReviewDocumentStage,
    PendingReviewStage,
    RejectedReviewStage,
    ReviewStage,
    VersionReviewStage,
    document_stage_for,
    review_stage_for,
    version_review_stage_for,
)
from app.domain.value_objects import DocumentNumber, SemanticVersion, TopicSlug
from app.domain.workflows import DocumentWorkflow, ReviewWorkflow, WorkflowModel

__all__ = [
    "ActiveDocumentStage",
    "AnyPermissionCapability",
    "ApprovedDocumentStage",
    "ApprovedReviewStage",
    "ArchivedDocumentStage",
    "CanAssignCompanies",
    "CanPublish",
    "CancelledReviewStage",
    "CustomerInvitationTenantSpec",
    "CustomerUserCapability",
    "DateRangeSpec",
    "DocumentAggregate",
    "DocumentAccessCapability",
    "DocumentFactory",
    "DocumentStage",
    "DocumentDraftOrActiveSpec",
    "DocumentDraftStatusSpec",
    "DocumentNumber",
    "DocumentWorkflow",
    "DraftDocumentStage",
    "InternalUserCapability",
    "InvitationAggregate",
    "InvitationFactory",
    "InvitationPendingStatusSpec",
    "InvitationResendableSpec",
    "ManagerVisibilityRoleSpec",
    "ManageUserCapability",
    "NoReviewStage",
    "PendingReviewDocumentStage",
    "PendingReviewStage",
    "PermissionCapability",
    "RejectedReviewStage",
    "RoleAccessSpec",
    "Result",
    "ReviewApprovalCapability",
    "ReviewAggregate",
    "ReviewApprovableVersionSpec",
    "ReviewStage",
    "ReviewPendingStatusSpec",
    "ReviewSubmitterMatchesSpec",
    "ReviewWorkflow",
    "RoleCapability",
    "TenantScopeSpec",
    "SemanticVersion",
    "TopicSlug",
    "VersionReviewStage",
    "VersionFactory",
    "VisibilitySpec",
    "WorkflowModel",
    "document_stage_for",
    "review_stage_for",
    "version_review_stage_for",
]
