export const PLATFORM_UPLOAD_MAX_SIZE_BYTES = 50 * 1024 * 1024
export const PLATFORM_UPLOAD_MAX_SIZE_MB = PLATFORM_UPLOAD_MAX_SIZE_BYTES / (1024 * 1024)
export const PLATFORM_UPLOAD_MAX_SIZE_LABEL = `${PLATFORM_UPLOAD_MAX_SIZE_MB}MB`
